os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.11.4"
jdk:
    - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.mvn
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.4
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - wget -qO- https://get.docker.com/ | sh
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker build -q -t gamecraft/gamecraft-registry:travis ./gamecraft-registry
  - docker images
  - docker run --name gamecraft-registry -p 8761:8761 -d -t gamecraft/gamecraft-registry:travis
install:
  - mvn clean install
script:
#  - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName=gamecraft
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
