version: '2'
services:
    gamecrafttwitternotificationmanager-app:
        image: gamecrafttwitternotificationmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://gamecrafttwitternotificationmanager-mysql:3306/gamecrafttwitternotificationmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gamecrafttwitternotificationmanager-elasticsearch:9300
    gamecrafttwitternotificationmanager-mysql:
        extends:
            file: mysql.yml
            service: gamecrafttwitternotificationmanager-mysql
    gamecrafttwitternotificationmanager-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gamecrafttwitternotificationmanager-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
